name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r25b

      - name: Export NDK toolchain to PATH
        run: echo "${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Set linker (Cargo)
        run: |
          echo '[target.aarch64-linux-android]' >> .cargo/config.toml
          echo 'linker = "aarch64-linux-android21-clang"' >> .cargo/config.toml

      - name: Build
        run: cargo build --target aarch64-linux-android --release
