name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r26d

      - name: Add NDK toolchain to PATH
        run: echo "${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Print NDK path
        run: echo $NDK_HOME
      
      - name: List toolchain
        run: ls $NDK_HOME/toolchains/llvm/prebuilt/
  
      - name: Add clang to PATH
        run: |
          echo "${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Build
        run: cargo build --release --target aarch64-linux-android
